<?php
// Texto editable que se muestra en el formulario
$messageWebTabTitle = "Formulario de Pago";
$messagePaymentTitle = "Formulario de Pago";
$messagePaymentRadioSoles = "S/. Soles";
$messagePaymentRadioDolares = "$ USD";
$messagePaymentProductDescription = "Pago por servicios de transporte de Hanabitours S.A.C";
$messagePaymentButton = "Continuar";
$messagePaymentInstructions = "Este formulario le permtirá ingresar el monto a pagar por los servicios que solicita. Una vez ingresado el monto, usted será redireccionado a la plataforma de pago";
$messagePaymentCopyRight = "© 2017-2022 - Hanabitours - Perú";
$messagePaymentConfirmation = "Usted pagará la suma de:";

//Urls de logotipo e imagen de fondo
$urlImgLogo = "https://imagizer.imageshack.com/v2/1600x1200q90/922/4QNR8K.png";
$urlImgBackground = "https://imagizer.imageshack.com/v2/1600x1200q90/924/OukUFQ.jpg";

// Url de respuestas Aprovado, rechazado y pendiente , respectivamente
$approvedResponseUrl = "https://www.hanabitours.com";
$declinedResponseUrl = "http://www.hanabitours.com";
$pendingResponseUrl = "http://www.hanabitours.com";
$urlPaymentGatewayLogo = "https://api.openpay.pe/img/icons/logoOpenpayBlue.svg";

?>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title><?php echo $messageWebTabTitle ?></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
        </script>
        <!-- http://www.exadium.com/tools/online-url-encode-and-url-decode-tool/ -->
        <!-- https://codebeautify.org/html-to-php-converter -->
        <!-- http://php.net/manual/es/function.money-format.php -->
    
        <script type="text/javascript">
            function check() {

                currency = document.formOpenValue.currency;
                accountId = document.formOpenValue.accountId;
                chkPEN = document.getElementById("chkPEN");
                chkUSD = document.getElementById("chkUSD");

                if (chkPEN.checked) {
                    // accountId.value = "735103";
                    currency.value = "PEN";
                } else if (chkUSD.checked) {
                    // accountId.value = "739134";
                    currency.value = "USD";
                }
            }
        </script>
    </head>

    <style>
        html,
        body {
            height: 100%;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
            display: block;
            position: relative;
            background: url(<?php echo $urlImgBackground ?>) no-repeat center center fixed;
        }

        body::after {
            content: "";
            -webkit-background-size: cover;
            -moz-background-size: cover;
            background-size: cover;
            -o-background-size: cover;
            /*opacity: 0.5;*/
            filter: brightness(60%);
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            position: absolute;
            z-index: -1;   
        }

        .parent_form-open-value {
            width: 100%;
            display: flex;
            height: 80%;
            margin: 0;
        }

        .form-open-value {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
            background-color: white;
            border-radius: 1rem;
            opacity: 0.9;
            margin-left: 20%;
        }

        .form-open-value .form-title {
            padding: 20px;
            font-weight: 150;
            font-size: 2.5rem;
        }
        
        .form-open-value .float-form-line {
            padding: 2px;
        }
        
        .form-open-value .float-form-line .form-input-text {
            text-align: center;
            font-size: 1rem;
            position: relative;
            box-sizing: border-box;
            display: block;
            width: 50%;
            float: left;
            height: calc(2.25rem + 2px);
            padding: .375rem .75rem;
            line-height: 1.5;
            color: #495057;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid #ced4da;
            border-radius: .25rem;
            transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
        }
        
        .form-open-value .form-input-email {
            text-align: center;
            font-size: 1rem;
            position: relative;
            box-sizing: border-box;
            display: block;
            width: 100%;
            height: calc(2.25rem + 2px);
            padding: .375rem .75rem;
            line-height: 1.5;
            color: #495057;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid #ced4da;
            border-radius: .25rem;
            transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
        }

        .form-open-value .form-input-amount {
            text-align: center;
            font-size: 1rem;
            position: relative;
            box-sizing: border-box;
            display: block;
            width: 100%;
            height: calc(2.25rem + 2px);
            padding: .375rem .75rem;
            line-height: 1.5;
            color: #495057;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid #ced4da;
            border-radius: .25rem;
            transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
        }

        .form-open-value .form-instructions {
            font-weight: 100;
            font-size: 1rem;
        }

        .form-open-value .form-radio-currencies {
            margin: 1rem;
        }
        .form-open-value .style-payment-gatewway-logo {
            width: 35%;
        }
    

        .hanabiImage img {
            width: 70%;
            height: 70%;
        }
        
        /* For mobile phones: */
        @media only screen and (max-width: 576px) {
            .parent_form-open-value {
                width: 100%;
                display: flex;
                height: 80%;
                margin: 0;
            }


            .form-open-value {
                width: 100%;
                max-width: 330px;
                padding: 15px;
                margin: auto;
                background-color: white;
                border-radius: 1rem;
                opacity: 0.9; 
            }
        }
    </style>

    <body class="text-center">
        <!-- <div class="row"> -->
        <nav class="navbar navbar-light bg-dark">
            <a class="navbar-brand" href="#">
                <img src="<?php echo $urlImgLogo ?>" width="auto" height="63" alt="">
            </a>
        </nav>
        
        <div class="parent_form-open-value">
            <form name="formOpenValue" class="form-open-value" method="post" action="backend.php">
                <h1 class="form-title"><?php echo $messagePaymentTitle ?></h1>
                <div class="float-form-line">
                    <input class="form-input-text" type="text" name="txtName" id="txtName" placeholder="Nombres" required autofocus="">
                    <input class="form-input-text" type="text" name="txtLastname" id="txtLastname" placeholder="Apellidos" required>
                </div>
                
                <input class="form-input-email" type="email" name="txtEmail" id="txtEmail" placeholder="Correo electrónico" required>
                <input class="form-input-amount" type="hidden" value="" id="txtPhoneNumber" name="txtPhoneNumber" placeholder="Celular" pattern="(0\.((0[1-9]{1})|([1-9]{1}([0-9]{1})?)))|(([1-9]+[0-9]*)(\.([0-9]{1,2}))?)">
                <input class="form-input-amount" type="number" min="0.00" step="any" id="txtOpenAmount" name="txtOpenAmount" placeholder="Ingrese monto de pago" pattern="(0\.((0[1-9]{1})|([1-9]{1}([0-9]{1})?)))|(([1-9]+[0-9]*)(\.([0-9]{1,2}))?)" required="">


                <div class="form-radio-currencies">
                    <!-- Soles Radio Button -->
                    <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" name="chkCurrency" id="chkPEN" onclick="check()" checked>
                        <label class="form-check-label" for="materialInline1"><?php echo $messagePaymentRadioSoles ?></label>
                    </div>

                    <!-- Dollars radio button -->
                    <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" name="chkCurrency" id="chkUSD" onclick="check()">
                        <label class="form-check-label" for="materialInline2"><?php echo $messagePaymentRadioDolares ?></label>
                    </div>
                </div> 
                

                <input name="url" type="hidden"  value="https://sandbox-api.openpay.pe"> 
                <!--<input name="url" type="hidden" value="https://api.openpay.pe">-->

                <input name="merchantId" type="hidden" value="">
                <input name="accountId" type="hidden" value="">
                <input name="description" type="hidden" value="<?php echo $messagePaymentProductDescription ?>">
                <!--<input name="referenceCode" type="hidden" value="##">-->
                <input name="amount" type="hidden" value="##">
                <input name="tax" type="hidden" value="0">
                <input name="taxReturnBase" type="hidden" value="0">
                <input name="currency" type="hidden" value="PEN">
                <input name="lng" type="hidden" value="es" />

                <input name="approvedResponseUrl" type="hidden" value="<?php echo $approvedResponseUrl ?>" />
                <input name="declinedResponseUrl" type="hidden" value="<?php echo $declinedResponseUrl ?>" />
                <input name="pendingResponseUrl" type="hidden" value="<?php echo $pendingResponseUrl ?>" />

                <input name="test" type="hidden" value="0">
                <input name="buyerEmail" type="hidden" value="">

                <input name="messagePaymentButton" type="hidden" value="<?php echo $messagePaymentButton ?>">
                <input name="messagePaymentTitle" type="hidden" value="<?php echo $messagePaymentTitle ?>">
                <input name="urlImgLogo" type="hidden" value="<?php echo $urlImgLogo ?>">
                <input name="urlImgBackground" type="hidden" value="<?php echo $urlImgBackground ?>">
                <input name="messageWebTabTitle" type="hidden" value="<?php echo $messageWebTabTitle ?>">
                <input name="messagePaymentInstructions" type="hidden" value="<?php echo $messagePaymentInstructions ?>">
                <input name="messagePaymentCopyRight" type="hidden" value="<?php echo $messagePaymentCopyRight ?>">
                <input name="messagePaymentConfirmation" type="hidden" value="<?php echo $messagePaymentConfirmation ?>">
                <input name="urlPaymentGatewayLogo" type="hidden" value="<?php echo $urlPaymentGatewayLogo ?>"> 
                
                
                <input class="btn btn-lg btn-secondary btn-block" type="submit" name="btnFormOpenValue" value="<?php echo $messagePaymentButton ?>">
                <br></br>
                <p class="form-instructions"><?php echo $messagePaymentInstructions ?></p>
                <input type="image" class="style-payment-gatewway-logo" src="<?php echo $urlPaymentGatewayLogo ?>"> 
                <p class="mt-3 mb-1 text-muted"><?php echo $messagePaymentCopyRight ?></p>
            </form>
        </div>
    
    </body>

</html>
